spring:
  application:
    name: "springboot-openai-speach-to-text"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

espark:
  openai:
    apikey: ${OPENAI_API_KEY}
    apiUrl: https://api.openai.com/v1/audio/transcriptions
